// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ML_TrekkingTeamML.Model
{
    public class ModelInput
    {
        [ColumnName("SHIPMENT_CREATEDATE"), LoadColumn(0)]
        public float SHIPMENT_CREATEDATE { get; set; }


        [ColumnName("FIRST_EVENT"), LoadColumn(1)]
        public float FIRST_EVENT { get; set; }


        [ColumnName("LAST_EVENT"), LoadColumn(2)]
        public float LAST_EVENT { get; set; }


        [ColumnName("RECEIVER_ZIP"), LoadColumn(3)]
        public float RECEIVER_ZIP { get; set; }


        [ColumnName("RECEIVER_COUNTRY_IOS2"), LoadColumn(4)]
        public float RECEIVER_COUNTRY_IOS2 { get; set; }


        [ColumnName("SENDER_ZIP"), LoadColumn(5)]
        public float SENDER_ZIP { get; set; }


        [ColumnName("SENDER_COUNTRY_IOS2"), LoadColumn(6)]
        public float SENDER_COUNTRY_IOS2 { get; set; }


        [ColumnName("SHIPMENT_WEIGHT"), LoadColumn(7)]
        public float SHIPMENT_WEIGHT { get; set; }


    }
}
